//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoDoiTour.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTour
    {
        public string MaNV { get; set; }
        public string MaTour { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string NoiDungTour { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
