CREATE DATABASE QLNHANVIEN

GO

USE QLNHANVIEN

GO
CREATE TABLE ACCOUNT
(
	USERNAME NVARCHAR(15) NOT NULL PRIMARY KEY,
	PASS NVARCHAR(50) 
);
GO
CREATE TABLE PHONGBAN
(
	MAPHONG NVARCHAR(15) NOT NULL PRIMARY KEY,
	TENPHONG NVARCHAR(40),
	VITRI NVARCHAR(40)
);
GO
CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(15) NOT NULL PRIMARY KEY,
	HOTEN NVARCHAR(40),
	NGAYSINH DATE,
	NOISINH NVARCHAR(40),
	NGAYVL DATE,
	MAPHONG NVARCHAR(15) FOREIGN KEY REFERENCES PHONGBAN(MAPHONG)
);
GO

INSERT INTO ACCOUNT(USERNAME,PASS)
VALUES
		('admin','123'),
		('user1','123'),
		('user2','123');
GO
INSERT INTO PHONGBAN (MAPHONG,TENPHONG,VITRI)
VALUES
	('P001',N'PHÒNG KHTC',N'LẦU 1'),
	('P002',N'PHÒNGNHAN SỰ',N'LẦU 1'),
	('P003',N'PHÒNG KINH DOANH',N'LẦU 2');

GO
INSERT INTO NHANVIEN(MANV,HOTEN,NGAYSINH,NOISINH,NGAYVL,MAPHONG)
VALUES
	('NV001',N'TRẦN THỊ MỸ LỆ','1975-10-19',N'TP HCM','2011-03-20','P001'),
	('NV002',N'LƯƠNG THÁI HÀO','2000-10-19',N'TP HCM','2021-03-20','P001'),
	('NV003',N'NGUYỄN THỊ THU CÚC','1995-10-19',N'TP HCM','2018-03-20','P002');